import { createServerFn } from "@tanstack/react-start";
import { createClient } from "@supabase/supabase-js";
import { z } from "zod";
import type { Database } from "@/integrations/supabase/types";

function client(){ const url=process.env['SUPABASE_URL']; const key=process.env['SUPABASE_PUBLISHABLE_KEY']; if(!url||!key) throw new Error("Store service is unavailable"); return createClient<Database>(url,key,{auth:{persistSession:false},global:{fetch:(input,init)=>{const h=new Headers(init?.headers);if(key.startsWith('sb_'))h.delete('Authorization');h.set('apikey',key);return fetch(input,{...init,headers:h})}}}); }
const email=z.string().trim().email().max(255);
export const subscribe=createServerFn({method:"POST"}).inputValidator((v)=>z.object({email}).parse(v)).handler(async({data})=>{const {error}=await client().from("newsletter_subscribers").upsert({email:data.email});if(error)throw new Error(error.message);return{ok:true}});
export const sendContact=createServerFn({method:"POST"}).inputValidator((v)=>z.object({name:z.string().trim().min(2).max(100),email,phone:z.string().trim().max(30).optional(),message:z.string().trim().min(10).max(2000)}).parse(v)).handler(async({data})=>{const {error}=await client().from("contact_submissions").insert({...data,phone:data.phone??null});if(error)throw new Error(error.message);return{ok:true}});
const item=z.object({productId:z.string().uuid().nullable(),variantId:z.string().uuid().nullable(),productName:z.string().max(120),size:z.string().max(4),color:z.string().max(50),quantity:z.number().int().min(1).max(20),unitPrice:z.number().int().positive()});
export const placeOrder=createServerFn({method:"POST"}).inputValidator((v)=>z.object({email,phone:z.string().min(8).max(30),fullName:z.string().min(2).max(100),addressLine:z.string().min(8).max(300),city:z.string().min(2).max(80),postalCode:z.string().max(20).optional(),notes:z.string().max(500).optional(),paymentMethod:z.enum(["cod","jazzcash","easypaisa","bank_transfer","local_card"]),subtotal:z.number().int().nonnegative(),items:z.array(item).min(1).max(30)}).parse(v)).handler(async({data})=>{const db=client();const {data:order,error}=await db.from("orders").insert({email:data.email,phone:data.phone,full_name:data.fullName,address_line:data.addressLine,city:data.city,postal_code:data.postalCode??null,notes:data.notes??null,payment_method:data.paymentMethod,subtotal:data.subtotal,shipping:0,total:data.subtotal}).select("id,order_number").single();if(error||!order)throw new Error(error?.message??"Order could not be created");const {error:itemsError}=await db.from("order_items").insert(data.items.map(i=>({order_id:order.id,product_id:i.productId,variant_id:i.variantId,product_name:i.productName,size:i.size,color:i.color,quantity:i.quantity,unit_price:i.unitPrice})));if(itemsError)throw new Error(itemsError.message);return order;});