import { useEffect, useRef, useState } from "react";
import { Link } from "@tanstack/react-router";
import { gsap } from "gsap";
import { MessageCircle, ShoppingBag, X, Bot } from "lucide-react";
import { products, money } from "@/lib/catalog";
import { ProductImage } from "./product-image";
import { useStore } from "./store-context";
import { Button } from "./ui/button";

const faqs = [
  ["Do you deliver all over Pakistan?","Yes, free delivery nationwide, 3–5 business days."],
  ["Can I check the parcel before paying?","Yes, open-parcel/COD available — inspect before payment."],
  ["What is your return/exchange policy?","7-day easy return on unused, tagged items."],
  ["What payment methods do you accept?","Cash on Delivery, JazzCash, Easypaisa, and card payments via our secure Pakistani payment gateway."],
  ["How do I know my size?","Open the Size Guide accordion on each product page."],
  ["How can I track my order?","Your order confirmation includes a WhatsApp/SMS tracking link."],
  ["Do you offer wholesale/bulk orders?","Message us on WhatsApp for bulk inquiries."],
  ["How do I use a discount code?","Enter it at checkout in the promo code field."],
  ["Is the fabric pre-shrunk / how do I wash it?","See the Fabric & Care accordion on the product page."],
  ["How do I talk to a real person?","Tap the WhatsApp button below and our team will help."],
];

export function Overlays(){ const s=useStore(); const featured=products[3]; const quick=s.quick; const [chat,setChat]=useState(false); const [answer,setAnswer]=useState(0); const [fomo,setFomo]=useState(false); const fomoRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{ if(sessionStorage.getItem("mf-fomo-off")) return; const timer=window.setTimeout(()=>setFomo(true),10000); return()=>window.clearTimeout(timer); },[]);
  useEffect(()=>{ if(!fomo||!fomoRef.current) return; const tl=gsap.timeline({repeat:-1,repeatDelay:10}); tl.fromTo(fomoRef.current,{x:"-120%",opacity:0},{x:0,opacity:1,duration:.55,ease:"power3.out"}).to(fomoRef.current,{x:"-120%",opacity:0,duration:.45,ease:"power2.in",delay:2.6}); return()=>{tl.kill()}; },[fomo]);
  return <>
    {fomo&&featured&&<div ref={fomoRef} className="fixed bottom-4 left-4 z-40 grid w-[calc(100%-2rem)] max-w-sm grid-cols-[56px_minmax(0,1fr)] gap-3 border border-border bg-background p-3 shadow-2xl"><ProductImage product={featured} className="aspect-square"/><div className="min-w-0 pr-5"><strong className="block truncate text-xs">Someone recently bought a {featured.name}</strong><p className="mt-1 text-xs text-muted-foreground">12 minutes ago, from Lahore, PK</p></div><button aria-label="Dismiss recent purchase" onClick={()=>{setFomo(false);sessionStorage.setItem("mf-fomo-off","1")}} className="absolute right-2 top-2"><X className="size-3"/></button></div>}
    <div className="fixed bottom-5 right-5 z-50 flex flex-col gap-4"><button onClick={()=>setChat(!chat)} aria-label="Open frequently asked questions" className="grid size-14 place-items-center rounded-full bg-foreground text-background shadow-xl"><Bot/></button><a href="https://wa.me/923064777251" aria-label="Chat on WhatsApp" className="pulse-soft grid size-14 place-items-center rounded-full bg-whatsapp text-whatsapp-foreground shadow-xl"><MessageCircle/></a></div>
    {chat&&<div className="fixed bottom-40 right-4 z-50 w-[calc(100%-2rem)] max-w-sm border border-border bg-background shadow-2xl"><div className="flex items-center justify-between bg-foreground p-4 text-background"><strong>Ask Maryam</strong><button onClick={()=>setChat(false)} aria-label="Close FAQ chat"><X/></button></div><div className="max-h-[55vh] overflow-y-auto p-4"><p className="mb-4 text-sm text-muted-foreground">How can we help?</p>{faqs.map((f,i)=><button key={f[0]} onClick={()=>setAnswer(i)} className="mb-2 block w-full border-b border-border py-2 text-left text-sm font-medium">{f[0]}</button>)}<p className="mt-4 bg-muted p-3 text-sm">{faqs[answer]?.[1]??faqs[0]?.[1]}</p><a href="https://wa.me/923064777251" className="mt-3 flex items-center justify-center gap-2 bg-whatsapp p-3 text-sm font-bold text-whatsapp-foreground"><MessageCircle className="size-4"/> Talk to a real person</a></div></div>}
    {s.cartOpen&&<div className="fixed inset-0 z-[70] bg-foreground/40" onMouseDown={(e)=>{if(e.currentTarget===e.target)s.setCartOpen(false)}}><aside className="ml-auto flex h-full w-full max-w-md flex-col bg-background p-5"><div className="flex items-center justify-between border-b pb-4"><h2 className="font-display text-2xl">Your bag</h2><button onClick={()=>s.setCartOpen(false)} aria-label="Close cart"><X/></button></div><div className="flex-1 overflow-y-auto py-4">{s.cart.length===0?<div className="grid h-full place-items-center text-center"><div><ShoppingBag className="mx-auto mb-3 size-10 text-muted-foreground"/><p>Your bag is waiting for something beautiful.</p></div></div>:s.cart.map(i=><div key={i.product.slug+i.size} className="grid grid-cols-[72px_1fr_auto] gap-3 border-b py-3"><ProductImage product={i.product} className="aspect-[2/3]"/><div><strong className="font-display text-sm font-normal">{i.product.name}</strong><p className="text-xs text-muted-foreground">Size {i.size} · Qty {i.quantity}</p><p className="mt-1 text-sm text-primary">{money(i.product.price*i.quantity)}</p></div><button onClick={()=>s.remove(i.product.slug)} aria-label="Remove item"><X className="size-4"/></button></div>)}</div>{s.cart.length>0&&<div className="border-t pt-4"><div className="mb-2 flex justify-between font-semibold"><span>Subtotal</span><span>{money(s.cart.reduce((a,i)=>a+i.product.price*i.quantity,0))}</span></div><p className="mb-4 text-xs text-muted-foreground">You’ve unlocked free nationwide delivery.</p><Link to="/cart" onClick={()=>s.setCartOpen(false)} className="block bg-primary p-3 text-center text-xs font-bold uppercase tracking-widest text-primary-foreground">View bag & checkout</Link></div>}</aside></div>}
    {quick&&<div className="fixed inset-0 z-[80] grid place-items-center bg-foreground/50 p-4" onMouseDown={(e)=>{if(e.currentTarget===e.target)s.setQuick(null)}}><div className="relative grid w-full max-w-3xl bg-background md:grid-cols-2"><button onClick={()=>s.setQuick(null)} aria-label="Close quick view" className="absolute right-3 top-3 z-10 grid size-9 place-items-center rounded-full bg-background"><X/></button><ProductImage product={quick} className="aspect-[2/3]"/><div className="flex flex-col justify-center p-6"><p className="text-xs uppercase tracking-widest text-gold">{quick.fabric}</p><h2 className="mt-2 font-display text-3xl">{quick.name}</h2><p className="mt-2 text-xl font-semibold text-primary">{money(quick.price)}</p><p className="mt-4 text-sm text-muted-foreground">{quick.description}</p><div className="my-5 flex gap-2">{["S","M","L","XL"].map(x=><button key={x} className="grid size-10 place-items-center border border-border focus:border-primary">{x}</button>)}</div><Button onClick={()=>{s.add(quick);s.setQuick(null)}}>Add to bag</Button></div></div></div>}
  </>;
}