import { useEffect, useState, type ReactNode } from "react";
import { Link } from "@tanstack/react-router";
import { ChevronDown, Heart, Menu, Search, ShoppingBag, User, X } from "lucide-react";
import { AnimatePresence, motion } from "motion/react";
import { collections, products } from "@/lib/catalog";
import { useStore } from "./store-context";
import { ProductImage } from "./product-image";
import { Button } from "./ui/button";

export function SiteShell({children}:{children:ReactNode}){const s=useStore();const [compact,setCompact]=useState(false);const [menu,setMenu]=useState(false);const [search,setSearch]=useState(false);const [query,setQuery]=useState("");
 useEffect(()=>{const f=()=>setCompact(scrollY>80);addEventListener("scroll",f,{passive:true});return()=>removeEventListener("scroll",f)},[]);
 const matches=query?products.filter(p=>p.name.toLowerCase().includes(query.toLowerCase())).slice(0,4):products.slice(0,4);
 return <div className="min-h-screen bg-background text-foreground"><div className="ticker overflow-hidden bg-primary py-2 text-primary-foreground"><div className="ticker-track flex w-max gap-20 whitespace-nowrap text-[10px] font-semibold uppercase tracking-[.18em]"><span>Free delivery across Pakistan</span><span>Flat 30% off selected styles</span><a href="https://wa.me/923064777251">Order on WhatsApp · 0306 4777251</a><span>Open parcel before payment</span><span>Free delivery across Pakistan</span><span>Flat 30% off selected styles</span></div></div>
 <header className={`sticky top-0 z-50 border-b border-border bg-background/95 backdrop-blur transition-all ${compact?"py-1":"py-2"}`}><div className="mx-auto grid max-w-[1440px] grid-cols-[auto_1fr_auto] items-center px-4 lg:px-8"><button className="lg:hidden" onClick={()=>setMenu(true)} aria-label="Open menu"><Menu/></button><div className="hidden lg:block"/><Link to="/" className={`justify-self-center font-brand text-gold transition-all ${compact?"text-2xl":"text-4xl"}`}>Maryam Fashions</Link><div className="flex items-center justify-end gap-3"><button onClick={()=>setSearch(true)} aria-label="Search"><Search className="size-5"/></button><Link to="/account" aria-label="Account" className="hidden sm:block"><User className="size-5"/></Link><Link to="/wishlist" aria-label="Wishlist" className="relative hidden sm:block"><Heart className="size-5"/>{s.wishlist.length>0&&<b className="badge">{s.wishlist.length}</b>}</Link><button onClick={()=>s.setCartOpen(true)} aria-label="Cart" className="relative"><ShoppingBag className="size-5"/>{s.cart.length>0&&<b className="badge">{s.cart.reduce((a,i)=>a+i.quantity,0)}</b>}</button></div></div>
 <nav className={`mx-auto hidden max-w-[1440px] items-center justify-center gap-8 px-6 text-[11px] font-semibold uppercase tracking-[.12em] transition-all lg:flex ${compact?"h-8":"h-11"}`}>{([{slug:"new-arrivals",name:"New Arrivals"},{slug:"eid-collection",name:"Eid Collection"},{slug:"festive-wear",name:"Festive Wear"}] as const).map(x=><Link key={x.slug} to="/collections/$slug" params={{slug:x.slug}}>{x.name}</Link>)}<NavDrop label="Luxury Lawn" items={[{slug:"luxury-lawn",name:"Luxury Lawn"},{slug:"luxury-pret",name:"Luxury Pret"}]}/><Link to="/collections/$slug" params={{slug:"riwaayat"}}>Riwaayat</Link><NavDrop label="Sale" items={[{slug:"sale",name:"Sale"},{slug:"flat-30-off",name:"Flat 30% Off"}]}/><Link to="/collections/$slug" params={{slug:"wedding-wears"}}>Wedding Wears</Link></nav></header>
 <AnimatePresence>{menu&&<motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-[70] bg-foreground/40" onClick={()=>setMenu(false)}><motion.aside initial={{x:"-100%"}} animate={{x:0}} exit={{x:"-100%"}} onClick={e=>e.stopPropagation()} className="h-full w-[86%] max-w-sm bg-background p-6"><div className="flex items-center justify-between"><span className="font-brand text-3xl text-gold">Maryam Fashions</span><button onClick={()=>setMenu(false)}><X/></button></div><div className="mt-8 space-y-1">{collections.map(c=><Link key={c[0]} to="/collections/$slug" params={{slug:c[0]}} onClick={()=>setMenu(false)} className="block border-b border-border py-3 text-sm uppercase tracking-wider">{c[1]}</Link>)}</div></motion.aside></motion.div>}</AnimatePresence>
 {search&&<div className="fixed inset-0 z-[80] bg-foreground/45" onClick={()=>setSearch(false)}><div className="bg-background p-5 md:p-8" onClick={e=>e.stopPropagation()}><div className="mx-auto max-w-4xl"><div className="flex items-center gap-3 border-b border-foreground pb-2"><Search/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search embroidered lawn, festive wear..." className="min-w-0 flex-1 bg-transparent py-2 outline-none"/><button onClick={()=>setSearch(false)}><X/></button></div><p className="mt-5 text-xs uppercase tracking-widest text-muted-foreground">{query?"Search results":"Popular products"}</p><div className="mt-3 grid grid-cols-2 gap-3 md:grid-cols-4">{matches.map(p=><Link key={p.slug} to="/product/$slug" params={{slug:p.slug}} onClick={()=>setSearch(false)}><ProductImage product={p} className="aspect-[2/3]"/><span className="mt-2 block text-sm">{p.name}</span></Link>)}</div><Link to="/search" search={{q:query}} onClick={()=>setSearch(false)} className="mt-6 block text-center text-xs font-bold uppercase tracking-widest text-primary">View all results</Link></div></div></div>}
 <main>{children}</main><Footer/></div>}

function NavDrop({label,items}:{label:string;items:readonly {slug:string;name:string}[]}){return <div className="group relative py-3"><button className="flex items-center gap-1">{label}<ChevronDown className="size-3"/></button><div className="invisible absolute left-1/2 top-full w-48 -translate-x-1/2 border border-border bg-background p-2 opacity-0 shadow-xl transition group-hover:visible group-hover:opacity-100">{items.map(x=><Link key={x.slug} to="/collections/$slug" params={{slug:x.slug}} className="block p-3 hover:bg-muted">{x.name}</Link>)}</div></div>}
function Footer(){return <footer className="mt-20 border-t border-border bg-footer text-footer-foreground"><div className="mx-auto grid max-w-[1440px] gap-10 px-5 py-14 md:grid-cols-4 lg:px-8"><div><div className="font-brand text-3xl text-gold">Maryam Fashions</div><p className="mt-4 text-sm leading-6 text-footer-muted">Thoughtfully designed Pakistani lawn and embroidered suits, delivered nationwide.</p><p className="mt-3 text-sm">WhatsApp: 0306 4777251<br/>hello@maryamfashions.pk</p></div><div><h3 className="footer-title">Collections</h3>{collections.slice(0,6).map(c=><Link key={c[0]} to="/collections/$slug" params={{slug:c[0]}} className="footer-link">{c[1]}</Link>)}</div><div><h3 className="footer-title">Customer care</h3>{[["/shipping-policy","Shipping Policy"],["/refund-policy","Refund Policy"],["/privacy-policy","Privacy Policy"],["/terms","Terms of Service"],["/contact","Contact Information"],["/about","Our Story"]].map(x=><Link key={x[0]} to={x[0] as "/about"} className="footer-link">{x[1]}</Link>)}</div><div><h3 className="footer-title">Private list</h3><p className="text-sm text-footer-muted">Receive 10% off your first order and preview new edits.</p><form className="mt-4 flex" onSubmit={e=>e.preventDefault()}><input type="email" required aria-label="Newsletter email" placeholder="Email address" className="min-w-0 flex-1 bg-background px-3 text-foreground"/><Button type="submit">Join</Button></form><div className="mt-5 flex flex-wrap gap-2 text-[10px]"><span className="pay-pill">COD</span><span className="pay-pill">JazzCash</span><span className="pay-pill">Easypaisa</span><span className="pay-pill">Bank Transfer</span><span className="pay-pill">VISA</span><span className="pay-pill">Mastercard</span></div></div></div><div className="border-t border-footer-border py-5 text-center text-xs text-footer-muted">© 2026 Maryam Fashions. Made with care in Pakistan.</div></footer>}
